[package]
name = "gxrfetch"
description = "A simple and very customizable fetch program"
version = "0.8.1"
edition = "2021"
license = "GPL-3.0"

[dependencies]
termion = "1.5.6"
systemstat = "0.1.10"
fsi = "0.1.0"
home = "0.5.3"
nixinfo = "0.3.3"
regex = "1.5.5"
lazy_static = "1.4.0"
