[package]
name = "gxrfetch"
description = "A simple but very customizable fetch program"
version = "0.8.0"
edition = "2021"
license = "GPL-3.0"

[dependencies]
termion = "1.5.6"
systemstat = "*"
fsi = "*"
home = "0.5.3"
nixinfo = "*"
regex = "*"
